config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Rails.application.routes.draw do
  constraints(SubdomainPresent) do
    authenticated :user do
      root 'home#project', as: :authenticated_root
    end
    root :to => redirect('/login')

    devise_for :users, path: '',
      path_names: { sign_up: '', sign_in: 'login', sign_out: 'logout' }
    namespace :manager do
      get  '/',          to: 'dashboard#index'
      get  'dashboard',  to: 'dashboard#index'
      get  'profile',    to: 'dashboard#profile'
      get  'employees',  to: 'users#index'
      get  'employees/new',  to: 'users#new'
      post 'employees/new',  to: 'users#add_user'

      resources :categories
      resources :products
      resources :businesses
    end

    namespace :menu do
      get '/',     to: 'products#index'
      get 'index', to: 'products#index'
    end
  end

  constraints(SubdomainBlank) do
    root 'home#index'
    get  'signup', to: 'accounts#new'
    post 'signup', to: 'accounts#create'
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  before_save :set_username


  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  devise :uid, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   validates :email, presence: true, length: { maximum: 255 },
                          format: { with: VALID_EMAIL_REGEX },
                          uniqueness: { case_sensitive: false }

   validates :password, presence: true, length: { minimum: 8 }
   validates :first_name, presence: true
   validates :last_name,  presence: true
   validates :username, uniqueness: { case_sensitive: false }

   def full_name
     self.first_name.capitalize + ' ' + self.last_name.capitalize
   end

   def get_account
     if self.admin?
        current = Apartment::Tenant.current
        Apartment::Tenant.switch!('public')
        account = Account.where(subdomain: current)
        Apartment::Tenant.switch!(current)
        account
      end
   end

   scope :employees, -> {where(admin: false)}
   scope :managers, -> {where(admin: true)}

   private

   def set_username
     self.username = self.first_name + self.last_name if username.nil?
   end

end

app/controllers/manager/base_manager_controller.rb
class Manager::BaseManagerController < ApplicationController
  layout 'manager'

end

app/controllers/manager/businesses_controller.rb
class Manager::BusinessesController < Manager::BaseManagerController
  before_action :set_business, only: [:show, :edit, :update]

  def show
  end


  def new
    if @business = Business.first.present?
      redirect_to edit_manager_business_path(Business.first.id)
    else
    @business = Business.new
    end
  end

  def create
    @business = Business.create(business_params)
    @business.save!
    redirect_to manager_path
  end

  def edit
  end

  def update
    @business.update_attributes(business_params)
    @business.save
    redirect_to manager_path
  end

  private

  def set_business
    @business = Business.first
  end

  def business_params
    params.require(:business).permit(:name,:description,:address,:city,:postal,
                                    :email,:phone,:twitter,:facebook,:website)
  end
end

app/controllers/manager/categories_controller.rb
class Manager::CategoriesController < Manager::BaseManagerController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(categories_params)
    if @category.save!
      redirect_to manager_categories_path
    else
      render :new
    end
  end

  private

  def categories_params
    params.require(:category).permit(:name,:parent_id)
  end
end

app/controllers/manager/dashboard_controller.rb
class Manager::DashboardController < Manager::BaseManagerController
  def index
  end

  def profile
  end
end

app/controllers/manager/products_controller.rb
class Manager::ProductsController < Manager::BaseManagerController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def show
  end

  def create
    @product = Product.create(products_params)
    if @product.save!
      redirect_to manager_products_url
    else
      render :new
    end
  end

  def edit
  end


  def update
    @product.update_attributes(products_params)
    if @product.save!
      redirect_to manager_products_url
    else
      render :edit
    end
  end

  def destroy
    if @product.destroy!
      redirect_to products_path
    else
      render @product
    end
  end

private

  def set_product
    @product = Product.find(params[:id])
  end

  def products_params
    prices_keys = params[:product].try(:fetch, :price, {}).keys
    params.require(:product).permit(:title,:duration, :description,:ingredients,
                                    :category_id,:image, price: prices_keys)
  end

end

app/controllers/manager/users_controller.rb
class Manager::UsersController < Manager::BaseManagerController

  def index
    @users = User.all
  end
  def new
    @user = User.new
  end

  def add_user
    @user = User.new(user_params)
    if @user.save!
      redirect_to manager_employees_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit( :first_name, :last_name, :password, :admin,
                                  :username, :email, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def add_user
    @user = User.new(user_params)
     if @user.save!
       redirect_to root_path
     else
       render :new
     end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name,
                                 :username, :admin, :email, :password,
                                 :password_confirmation)
  end
end

app/views/manager/users/_user.html.erb
<div class="row">
  <div class="col-md-6">
    <%=user.full_name%>
  </div>
  <div class="col-md-5">
    <p> <%=user.email%></p>
  </div>
  <div class="col-md-1">
    <p>Delete</p>
  </div>
  </div>
  <hr style="margin-top: 0rem;">

app/views/manager/users/index.html.erb
<div class="padding">
  <div class="row">
    <div class="col-md-10">
      <h1 class='hi1' >Employees</h1>
    </div>
    <div class="col-md-2">
      <%=link_to "Add new User", manager_employees_new_path, class:'btn btn-regular',
          style:'background:#2996cc; color:white;'%>
    </div>
  </div>
  <hr>
  <div class="padding">
    <%@users.managers.each do |user|%>
        <%= render 'user', user: user%>
    <%end%>
    <%if @users.employees.empty?%>
    <div class="no_product">
        <p>logo</p>
        <div class="no_product_header">
          <h1 class="no_product_h1">Add new Employe</h1>
          <p class="no_product_p">Add employees with names, email and password to help them get started taking orders.</p>
          <%=link_to "Add new User", manager_employees_new_path, class:'btn btn-regular',
              style:'background:#2996cc; color:white;'%>
        </div>
    </div>
    <%else%>
      <%@users.employees.each do |user|%>
          <%= render 'user', user: user%>
      <%end%>
  <%end%>
</div>
</div>

app/views/manager/users/new.html.erb
<div class="padding">
  <h1 class='hi1' >New Employees</h1>
  <hr>
<%= form_for User.new , :url => {:action => "add_user"}, class:'p-x-xs' do |user| %>
<div class="row">
  <div class="col-md-6">
    <div class="form-group">
      <%= user.label :first_name, class:'form-control-label'%>
      <%= user.text_field :first_name, class:'form-control', placeholder:'First Name' %>
    </div>
  </div>
  <div class="col-md-6">
    <div class="form-group">
      <%= user.label :last_name, class:'form-control-label'%>
      <%= user.text_field :last_name, class:'form-control', placeholder:'Last Name' %>
    </div>
  </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= user.label :username, class:'form-control-label'%>
        <%= user.text_field :username, class:'form-control', placeholder:'Username' %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= user.label :email, class:'form-control-label'%>
        <%= user.email_field :email, class:'form-control', placeholder:'Email' %>
      </div>
    </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= user.label :password, class:'form-control-label'%>
          <%= user.password_field :password, class:'form-control', placeholder:'Password' %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= user.label :email, class:'form-control-label'%>
          <%= user.password_field :password_confirmation, class:'form-control', placeholder:'Password Confirmation' %>
        </div>
      </div>
      </div>

      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= user.label 'Role', class:'form-control-label'%>
            <%= user.select :admin, [['Employee', false], ['Admin', true]], selected: false, class:'selectpicker' %>
          </div>
        </div>
        <div class="col-md-6">,
          <div class="form-group">
            <%=user.submit 'Save Employee',class:'btn btn-regular' ,style:'background:#2996cc; color:white;'%>
          </div>
        </div>
        </div>
<%end%>
</div>