config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Rails.application.routes.draw do
  constraints(SubdomainPresent) do
    authenticated :user do
      root 'home#project', as: :authenticated_root
    end
    root :to => redirect('/login')

    devise_for :users, path: '',
      path_names: { sign_up: '', sign_in: 'login', sign_out: 'logout' }
    namespace :manager do
      get  '/',          to: 'dashboard#index'
      get  'dashboard',  to: 'dashboard#index'
      get  'profile',    to: 'dashboard#profile'
      get  'employees',  to: 'users#index'
      get  'employees/new',  to: 'users#new'
      post 'employees/new',  to: 'users#add_user'

      resources :categories
      resources :products
      resources :businesses
    end

    namespace :menu do
      get '/',     to: 'products#index'
      get 'index', to: 'products#index'
    end
  end

  constraints(SubdomainBlank) do
    root 'home#index'
    get  'signup', to: 'accounts#new'
    post 'signup', to: 'accounts#create'
  end
end

app/controllers/manager/dashboard_controller.rb
class Manager::DashboardController < Manager::BaseManagerController
  def index
  end

  def profile
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/manager/dashboard/commons/_aside.html.erb
<!-- aside -->
<div id="aside" class="app-aside modal fade nav-expand">
  <div class="left navside black dk" layout="column">
    <div class="navbar no-radius">
      <!-- brand -->
      <a class="navbar-brand">
        <div ui-include="'../assets/images/logo.svg'"></div>
        <%= image_tag 'logo.png'%>
        <span class="hidden-folded inline"><%= current_user.username%></span>
      </a>
      <!-- / brand -->
    </div>
    <div flex-no-shrink="">
        <div class="nav-fold"><a href="#/app/page/profile" ui-sref="app.page.profile"><span class="pull-left">
          <%= image_tag 'a2.jpg', class:'w-40 r'%>  </span>
          <span class="clear hidden-folded p-x">
            <span class="block _500"><%= current_user.full_name%></span>
             <small class="block text-muted">Administrator</small></span></a>
           </div>
    </div>
    <div flex-no-shrink>
      <div ui-include="'../views/blocks/aside.top.2.html'"></div>
    </div>
    <div flex class="hide-scroll">
      <nav class="scroll nav-stacked nav-active-primary">

          <ul class="nav" ui-nav>
            <li class="nav-header hidden-folded">
              <small class="text-muted">Main</small>
            </li>
            <li>
              <%=link_to 'Home', manager_dashboard_path%>
            </li>
            <li>
              <%=link_to 'Products', manager_products_path%>
            </li>
            <li>
              <%=link_to 'Categories', manager_categories_path%>
            </li>
            <li>
              <%=link_to 'Employees', manager_employees_path%>
            </li>


            <li class="nav-header hidden-folded">
              <small class="text-muted">Help</small>
            </li>

            <li class="hidden-folded" >
              <a href="docs.html" >
                <span class="nav-text">Documents</span>
              </a>
            </li>

          </ul>
      </nav>
    </div>
    <div flex-no-shrink="">
      <nav ui-nav="">
        <ul class="nav">
            <li class="no-bg">
                <span class="nav-icon">
                  <i class="material-icons"></i>
                </span>
                  <%= link_to destroy_user_session_path, method: :delete do %>
                  <span class="nav-text"> Logout</span>
                  <%end%>
            </li>
          </ul>
        </nav>
    </div>
  </div>
</div>
<!-- / aside -->

app/views/manager/dashboard/commons/_navbar.html.erb
<div id="content" class="app-content box-shadow-z1" role="main">
  <div class="app-header white box-shadow">
      <div class="navbar" style="min-height: 0rem;">
          <a data-toggle="modal" data-target="#aside" class="navbar-item pull-left hidden-lg-up">
            <i class="material-icons">&#xe5d2;</i>
          </a>
      </div>
  </div>
  <div class="app-footer">
    <div class="p-a text-xs">
      <div class="pull-right text-muted">
        &copy; Copyright <strong>2017</strong> <span class="hidden-xs-down">- Built with Love v1.0</span>
        <a ui-scroll-to="content"><i class="fa fa-long-arrow-up p-x-sm"></i></a>
      </div>
      <div class="nav">
        <a class="nav-link" href="../">About</a>
        <span class="text-muted">-</span>
        <a class="nav-link label accent" href="#">Get it</a>
      </div>
    </div>
  </div>